version: "3"

services:
  ravendb:
    image: ravendb/ravendb
    volumes:
      - ravendb-data:/opt/RavenDB/Server/RavenData    
    container_name: ec-ravendb
    hostname: ravendbserver
    networks: 
      - ravendbnet
    ports:
      - 8080:8080
      - 38888:38888
    environment:
      RAVEN_Setup_Mode: "None"
      RAVEN_License_Eula_Accepted: "true"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    volumes:
      - dbsql-data:/var/opt/mssql
    container_name: ec-sqlserver-2017-ubuntu
    hostname: sqlserver
    networks: 
      - sqlservernet
    ports:
      - 1433:1433
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: EmergingB00king@2019
      MSSQL_PID: Express

  kafkaserver:
    image: spotify/kafka:latest
    container_name: ec-kafka
    hostname: kafkaserver
    networks:
      - kafkanet
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_PORT: 9092

  kafka_manager:
    image: mzagar/kafka-manager-docker:1.3.3.4
    container_name: ec-kafkamanager
    networks:
      - kafkanet
    ports:
      - 9000:9000
    links:
      - kafkaserver
    environment:
      ZK_HOSTS: "kafkaserver:2181"

volumes:
  ravendb-data:
  dbsql-data:          
networks:
  kafkanet:
  ravendbnet:
  sqlservernet: